name: tfgpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotli-python=1.0.9
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.16.0
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=41.0.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - icu=58.2
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - json5=0.9.6
  - jsonschema=4.19.2
  - jupyter=1.0.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyterlab=3.6.3
  - jupyterlab_widgets=3.0.9
  - krb5=1.20.1
  - libclang13=14.0.6
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - openssl=3.0.12
  - parso=0.8.3
  - pickleshare=0.7.5
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qtconsole=5.5.0
  - qtpy=2.4.1
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.5
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - yaml=0.2.5
  - y-py=0.5.9
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - astunparse==1.6.3
    - cachetools==5.3.2
    - charset-normalizer==3.3.2
    - efficientnet==1.0.0
    - flatbuffers==23.5.26
    - gast==0.4.0
    - google-auth==2.27.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.60.0
    - h5py==3.10.0
    - idna==3.6
    - image-classifiers==1.0.0
    - imageio==2.33.1
    - importlib-metadata==7.0.1
    - joblib==1.3.2
    - keras==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lazy-loader==0.3
    - libclang==16.0.6
    - markdown==3.5.2
    - markupsafe==2.1.4
    - networkx==3.2.1
    - numpy==1.26.3
    - oauthlib==3.2.2
    - opencv-python==4.9.0.80
    - opt-einsum==3.3.0
    - pandas==2.2.0
    - pip
    - pillow==10.2.0
    - protobuf==3.19.6
    - psutil==5.9.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.22.0
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - segmentation-models==1.0.1
    - tensorboard==2.10.1
    - tensorflow==2.10.0
    - tensorflow-addons==0.22.0
    - tensorflow-estimator==2.10.0
    - tensorflow-gpu==2.10.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.4.0
    - threadpoolctl==3.2.0
    - tifffile==2024.1.30
    - tqdm==4.66.1
    - typeguard==2.13.3
    - typing-extensions==4.9.0
    - urllib3==2.2.0
    - werkzeug==3.0.1
    - wrapt==1.16.0
    - zipp==3.17.0
